name: Java CI

on:
  push:
    branches:
    - 1.15
  pull_request:
    branches:
    - 1.15
 
jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download BuildTools
      run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - name: Test with Gradle
      run: ./gradlew clean build -x test
      
